api:
  host: "0.0.0.0"
  port: 8000
  debug: false
  
openai:
  model: "gpt-4"
  max_tokens: 1000
  temperature: 0.3
  
report:
  sections:
    - "Clinical History"
    - "Findings" 
    - "Impression"
    - "Recommendations"
  
  confidence_threshold: 0.7
  max_findings: 10