model:
  image_classifier:
    backbone: "resnet50"
    pretrained: true
    num_classes: 14
    dropout_rate: 0.3
    
  feature_extractor:
    embedding_dim: 512
    use_attention: true
    
preprocessing:
  image_size: [224, 224]
  normalize_mean: [0.485, 0.456, 0.406]
  normalize_std: [0.229, 0.224, 0.225]
  
pathologies:
  - "Atelectasis"
  - "Cardiomegaly" 
  - "Effusion"
  - "Infiltration"
  - "Mass"
  - "Nodule"
  - "Pneumonia"
  - "Pneumothorax"
  - "Consolidation"
  - "Edema"
  - "Emphysema"
  - "Fibrosis"
  - "Pleural_Thickening"
  - "Hernia"